version: '3.9'
services:
  blog-map.server:
    image: node:12-alpine
    working_dir: /usr/app
    container_name: blog-map.server
    command: npm start
    volumes:
      - ./:/usr/app
    ports:
      - 3001:${EXPRESS_PORT}
